export const MsgConstant = {
  TECHNICAL_ERROR_OCCURED: 'Some technical error occured',
  SERVER_ERROR_OCCURED: 'Server error occured',

  CODE_GET_PRODUCT_DETAIL_200: 'GET_PRODUCT_DETAIL_200',
  CODE_SAVE_PRODUCT_DETAIL_200: 'SAVE_PRODUCT_DETAIL_200',
  CODE_UPDATE_PRODUCT_DETAIL_200: 'UPDATE_PRODUCT_DETAIL_200',
  CODE_DELETE_PRODUCT_DETAIL_200: 'DELETE_PRODUCT_DETAIL_200',
};
